### ISSUE TITLE
definer ('eulims'@'%') does not exist

### ISSUE THREAD

**Issue by Arlbalest** [grapajaneedi/eulims#61]
OS: Windows Server 2012 R2
Server application: 
PHP 7.3.7
MySQL 5.6.25

Case:
Cloned the eUlims using git, and execute all mysql dump files:
 eulims, eulims_address, eulims_inventory, eulims_lab, eulims_referral_lab.

After configuration, following error occurs on testing the system:
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('eulims'@'%') does not exist' in C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\db\Command.php:1258
Stack trace:
#0 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\db\Command.php(1258): PDOStatement->execute()
#1 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\db\Command.php(1148): yii\db\Command->internalExecute('Call eulims_lab...')
#2 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\db\Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 C:\xampp\htdocs\ulims-latest\frontend\controllers\SiteController.php(156): yii\db\Command->queryAll()
#4 [internal function]: frontend\controllers\SiteController->actionIndex()
#5 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('', Array)
#8 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('', Array)
#9 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 C:\xampp\htdocs\ulims-latest\frontend\web\index.php(20): yii\base\Application->run()
#11 {main}

Next exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('eulims'@'%') does not exist
The SQL being executed was: Call eulims_lab.spGetDashboardDetails(0,11,0,0);' in C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\db\Schema.php:664
Stack trace:
#0 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\db\Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'Call eulims_lab...')
#1 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\db\Command.php(1148): yii\db\Command->internalExecute('Call eulims_lab...')
#2 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\db\Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 C:\xampp\htdocs\ulims-latest\frontend\controllers\SiteController.php(156): yii\db\Command->queryAll()
#4 [internal function]: frontend\controllers\SiteController->actionIndex()
#5 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('', Array)
#8 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('', Array)
#9 C:\xampp\htdocs\ulims-latest\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 C:\xampp\htdocs\ulims-latest\frontend\web\index.php(20): yii\base\Application->run()
#11 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 1449
    [2] => The user specified as a definer ('eulims'@'%') does not exist
)

**Comment by grapajaneedi** [comment]
delete the definer of the stored procedure
